Repository fastlane/ci, pull requests merged in 2018-04, with the labels that each got.

#531 Add First user story
  docs/user_stories/README.md
  docs/user_stories/debug_failed_build.md
Labels: use case

#656 List of Projects on Dashboard
  web/app/app-routing.module.ts
  web/app/app.module.ts
  web/app/common/constants.ts
  web/app/dashboard/dashboard.component.html
  web/app/dashboard/dashboard.component.scss
  web/app/dashboard/dashboard.component.spec.ts
  web/app/dashboard/dashboard.component.ts
  web/app/dashboard/test_helpers/mock_project_summary.ts
  web/app/models/project_summary.ts
  web/app/overview/overview.component.html
  web/app/overview/overview.component.scss
  web/app/overview/overview.component.spec.ts
  web/app/overview/overview.component.ts
  web/index.html
Labels: front-end

#745 [Proposal] Remove unused `commit_repo_changes` method in `UserService`
  app/services/user_service.rb
Labels: type: proposal

#747 Add support for management ENV variables for fastlane.ci
  app/features/all.rb
  app/features/build_runner/build_runner.rb
  app/features/environment_variables/README.md
  app/features/environment_variables/environment_variables_controller.rb
  app/features/environment_variables/views/environment_variables.erb
  app/features/environment_variables/views/forms/_environment_variables.erb
  app/features/global/navigation.erb
  app/services/configuration_repository_service.rb
  app/services/data_sources/environment_data_source.rb
  app/services/data_sources/json_environment_variable_data_source.rb
  app/services/environment_variable_service.rb
  app/services/services.rb
  app/shared/models/environment_variable.rb
  launch.rb
  spec/services/configuration_respository_service_spec.rb
Labels: complexity: large project

#769 Add project dialog and modularize dashboard
  web/app/app-routing.module.ts
  web/app/app.module.ts
  web/app/dashboard/add-project-dialog/add-project-dialog.component.html
  web/app/dashboard/add-project-dialog/add-project-dialog.component.scss
  web/app/dashboard/add-project-dialog/add-project-dialog.component.spec.ts
  web/app/dashboard/add-project-dialog/add-project-dialog.component.ts
  web/app/dashboard/dashboard.component.html
  web/app/dashboard/dashboard.component.spec.ts
  web/app/dashboard/dashboard.component.ts
  web/app/dashboard/dashboard.module.ts
Labels: front-end
