Repository fastlane/ci, pull requests merged in 2018-06, with the labels that each got.

#912 Inject actual build URL to ENV variables
  app/features/build_runner/build_runner.rb
Labels: Needs attention

#935 Add management of system settings
  agent/invocation.rb
  app/features-json/setting_json_controller.rb
  app/services/data_sources/json_setting_data_source.rb
  app/services/data_sources/setting_data_source.rb
  app/services/environment_variable_service.rb
  app/services/services.rb
  app/services/setting_service.rb
  app/shared/available_settings.rb
  app/shared/fastlane_ci_error.rb
  app/shared/models/setting.rb
  fastlane_app.rb
  launch.rb
  spec/features-json/setting_json_controller_spec.rb
Labels: needs attention

#919 Fix crash in xcode manager if no user is provided
  app/services/xcode_manager_service.rb
Labels: needs attention

#949 Check if server is configured on web app init and forward to onboarding
  app/features-json/setup_json_controller.rb
  launch.rb
  web/app/dashboard/dashboard.component.spec.ts
  web/app/dashboard/dashboard.module.ts
  web/app/project/project.component.spec.ts
  web/app/root/initialization.provider.spec.ts
  web/app/root/initialization.provider.ts
  web/app/root/root.module.ts
  web/app/services/data.service.spec.ts
  web/app/services/data.service.ts
Labels: needs attention

#927 Add Artifacts JSON API
  app/features-json/artifact_json_controller.rb
  app/features-json/view_models/artifact_view_model.rb
  app/features-json/view_models/build_view_model.rb
  app/shared/models/artifact.rb
  launch.rb
  spec/features-json/artifact_json_controller_spec.rb
Labels: needs attention

#1042 Proposal: Add running Build state
  app/shared/models/build.rb
Labels: type: proposal
